name: Set Up Rust
description: Installs the Rust toolchain

inputs:
  target:
    description: The `target` to pass to rustup when installing the toolchain
    required: false

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@9d7e65c320fdb52dcd45ffaa68deb6c02c8754d9 # v1.12.0
      with:
        cache-bin: false
        target: ${{ inputs.target }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install tree-sitter
      run: npm install -g tree-sitter-cli@0.22.2
      shell: bash
