image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ubuntu:22.04

stages:
  - test
  - release

test-and-build-arm64:
  stage: test
  script:
    - apt-get update
    - apt-get install -y git curl build-essential pkg-config libssl-dev
    - curl https://sh.rustup.rs -sSf  > rustup.sh && chmod a+x rustup.sh && ./rustup.sh -y && rm -f rustup.sh
    - source "$HOME/.cargo/env"
    - cargo build -r
    - cargo test
    - apt-get install -y python3 python3-requests
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l java
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l javascript
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l typescript
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l go
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l ruby
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l csharp
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l python
  variables:
    KUBERNETES_MEMORY_REQUEST: 6Gi
    KUBERNETES_MEMORY_LIMIT: 12Gi
    DD_SITE: datadoghq.com
  tags:
    - arch:arm64

test-and-build-amd64:
  stage: test
  script:
    - apt-get update
    - apt-get install -y git curl build-essential pkg-config libssl-dev
    - curl https://sh.rustup.rs -sSf  > rustup.sh && chmod a+x rustup.sh && ./rustup.sh -y && rm -f rustup.sh
    - source "$HOME/.cargo/env"
    - cargo build -r
    - cargo test
    - apt-get install -y python3 python3-requests
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l java
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l javascript
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l typescript
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l go
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l ruby
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l csharp
    - python3 misc/test-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server -l python
  variables:
    KUBERNETES_MEMORY_REQUEST: 6Gi
    KUBERNETES_MEMORY_LIMIT: 12Gi
    DD_SITE: datadoghq.com
  tags:
    - arch:amd64

trigger_internal_image:
  stage: release
  only:
    - main
  trigger:
    project: DataDog/images
    branch: ${DD_IMAGES_BRANCH}
    strategy: depend
  variables:
    DD_IMAGES_BRANCH: master
    IMAGE_VERSION: current
    IMAGE_NAME: datadog-static-analyzer
    RELEASE_TAG: ${CI_COMMIT_SHORT_SHA}
    BUILD_TAG:   ${CI_COMMIT_SHORT_SHA}
    TMPL_SRC_IMAGE: v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    RELEASE_STAGING: "true"
    RELEASE_PROD: "true"


