image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ubuntu:22.04

stages:
  - test

test-and-build-amd64:
  stage: test
  script:
    - apt-get update
    - apt-get install -y git curl build-essential pkg-config libssl-dev
    - curl https://sh.rustup.rs -sSf  > rustup.sh && chmod a+x rustup.sh && ./rustup.sh -y && rm -f rustup.sh
    - source "$HOME/.cargo/env"
    - cargo test
  variables:
    KUBERNETES_MEMORY_REQUEST: 6Gi
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: $CI_PROJECT_NAME
    DD_SITE: datadoghq.com
  tags:
    - arch:amd64

