[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21.2"
kernel = {path = "../kernel" }
derive_builder = "0.12.0"
glob-match = "0.2.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1.0"
serde_json = "1.0.96"
serde_derive = "1.0"
serde-sarif = "0.4.0"
serde_yaml = "0.9.21"
walkdir = "2.3.3"

[dev-dependencies]
assert-json-diff = "2.0.2"
