[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21.2"
deno_core = "0.194.0"
derive_builder = "0.12.0"
lazy_static = "1.4.0"
serde_v8 = "0.105.0"
serde_json = "1.0.96"
tree-sitter = "0.20.10"
serde = "1.0"
serde_derive = "1.0"
serde-sarif = "0.4.0"

[build-dependencies]
cc="*"
