[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
# workspace
anyhow = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
derive_builder = { workspace = true }
serde-sarif = { workspace = true }
# other
deno_core = "0.194.0"
lazy_static = "1.4.0"
serde_v8 = "0.105.0"
tree-sitter = "0.20.10"

[build-dependencies]
cc="*"
