[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21.2"
kernel = {path = "../kernel" }
derive_builder = "0.12.0"
serde = "1.0"
serde_json = "1.0.96"
serde_derive = "1.0"

[dev-dependencies]
assert-json-diff = "2.0.2"
