[package]
name = "common"
edition = "2021"
version.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { version = "1.0.203", features = ["derive"] }
derive_builder = { workspace = true }

# other
bstr = "1.9.1"