name: Code Coverage

on: [pull_request, push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Get Datadog credentials
        id: dd-sts
        uses: DataDog/dd-sts-action@2e8187910199bd93129520183c093e19aa585c75 # v1.0.0
        with:
          policy: datadog-static-analyzer
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@d50ec1d40c9c7a251e48a8f8810527d411553bdc
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Datadog
        run: |
          curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci
          /usr/local/bin/datadog-ci coverage upload lcov.info
        env:
          DD_API_KEY: ${{ steps.dd-sts.outputs.api_key }}
          DD_APP_KEY: ${{ steps.dd-sts.outputs.app_key }}
          DD_SITE: ${{ vars.DD_SITE }}