on: push
name: Run Integration tests
jobs:
  integration_tests:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ secrets.DD_SITE }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Stable + Rustfmt + Clippy
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
            default: true
      - name: Run Integration tests that the analyzer works with a repo
        run: ./misc/integration-test-repo.sh
      - name: Test all production rules
        run: |
          cargo build -r \
          sudo apt-get python3-requests \
          python misc/test-production-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server  -r python-best-practices \
          python misc/test-production-rules.py -c $PWD/target/release/datadog-static-analyzer -s $PWD/target/release/datadog-static-analyzer-server  -r python-security
