name: Run Integration tests

on:
  push:
    branches:
      - "**"
  pull_request:
  schedule:
    # run every day at 9am UTC
    - cron: '0 9 * * *'
  workflow_call:

jobs:
  test_scripts:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    strategy:
      matrix:
        scripts:
          - { file: './misc/integration-test-classification.sh', gha_alias: 'Artifact Classification' }
          - { file: './misc/integration-test-git.sh', gha_alias: 'Git' }
          - { file: './misc/integration-test-python.sh', gha_alias: 'Python' }
          - { file: './misc/integration-test-docker.sh', gha_alias: 'Docker' }
          - { file: './misc/integration-test-js-ts.sh', gha_alias: 'JavaScript/TypeScript' }
          - { file: './misc/integration-test-filter-rules.sh', gha_alias: 'Per-Path Rule Filtering' }
          - { file: './misc/integration-git-hooks.sh', gha_alias: 'Git Hooks' }
#          - { file: './misc/integration-test-r.sh', gha_alias: 'R' }
          - { file: './misc/integration-test-rust.sh', gha_alias: 'Rust' }
          - { file: './misc/integration-test-sql.sh', gha_alias: 'SQL' }
          - { file: './misc/integration-test-encoding.sh', gha_alias: 'File Encoding' }
          - { file: './misc/integration-test-default-config.sh', gha_alias: 'Default Config' }
          - { file: './misc/integration-test-secrets.sh', gha_alias: 'Secrets' }
    name: Run integration test - ${{ matrix.scripts.gha_alias }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/set-up-rust
      - name: Execute script
        run: ${{ matrix.scripts.file }}
