on:
  push:
  pull_request:
  schedule:
    # run every day at 9am UTC
    - cron:  '0 9 * * *'
name: Run Integration tests
jobs:
  test_scripts:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    strategy:
      matrix:
        scripts:
          - { file: './misc/integration-test-git.sh', gha_alias: 'Git' }
          - { file: './misc/integration-test-python.sh', gha_alias: 'Python' }
          - { file: './misc/integration-test-docker.sh', gha_alias: 'Docker' }
          - { file: './misc/integration-test-js-ts.sh', gha_alias: 'JavaScript/TypeScript' }
          - { file: './misc/integration-test-filter-rules.sh', gha_alias: 'Per-Path Rule Filtering' }
        runtime: ["stella", "ddsa"]
    name: Run integration test - ${{ matrix.scripts.gha_alias }} - Runtime ${{ matrix.runtime }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
      - uses: ./.github/actions/setup-build-env
      - uses: ./.github/actions/rust-cache
        with:
          cargo-target: x86_64-unknown-linux-gnu
          cargo-cache-key: release
      - name: Execute script
        run: ${{ matrix.scripts.file }}
        env:
          USE_DDSA: ${{ matrix.runtime == 'ddsa' && 'true' || '' }}
