on:
  push:
  pull_request:
  schedule:
    # run every day at 9am UTC
    - cron:  '0 9 * * *'
name: Run Integration tests
jobs:
  integration_test_git:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Stable + Rustfmt + Clippy
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
            default: true
      - name: Run Integration Test for Git
        run: ./misc/integration-test-git.sh
  integration_test_python:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Stable + Rustfmt + Clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          default: true
      - name: Run Integration Test for Python
        run: ./misc/integration-test-python.sh
  integration_test_docker:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Stable + Rustfmt + Clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          default: true
      - name: Run Integration Test for Docker
        run: ./misc/integration-test-docker.sh
  integration_test_jsts:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Stable + Rustfmt + Clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          default: true
      - name: Run Integration Test for JavaScript/TypeScript
        run: ./misc/integration-test-js-ts.sh
