on:
  push:
    branches:
      - "**"
  pull_request:

name: Check Code
jobs:
  check_code:
    strategy:
      matrix:
        config:
          - { os: macos-13, target: x86_64-apple-darwin, gha_alias: 'macOS x64 - ' }
        cargo_cmd:
          - { cmd_name: test, args: 'analysis::ddsa_lib::runtime::tests::query_execute_timeout', gha_alias: "Test" }
    name: ${{ matrix.config.gha_alias }}${{ matrix.cargo_cmd.gha_alias }}
    runs-on: ${{ matrix.config.os }}
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
      - name: Run cargo ${{ matrix.cargo_cmd.cmd_name }} ${{ matrix.cargo_cmd.args }}
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.cargo_cmd.cmd_name }}
          args: ${{ matrix.cargo_cmd.args }}
