on:
  push:
  pull_request:

name: Check Code
jobs:
  check_code:
    strategy:
      matrix:
        config:
          - { os: windows-latest, target: x86_64-pc-windows-msvc, gha_alias: 'Windows x64 - ' }
        cargo_cmd:
#          - { cmd_name: build, args: '--features=datadog-static-analyzer/secrets', gha_alias: "Build - Profile 'debug'" }
          - { cmd_name: test, args: '--workspace --features=datadog-static-analyzer/secrets', gha_alias: "Test" }
    name: ${{ matrix.config.gha_alias }}${{ matrix.cargo_cmd.gha_alias }}
    runs-on: ${{ matrix.config.os }}
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
      - uses: ./.github/actions/setup-build-env
      - uses: ./.github/actions/rust-cache
        with:
          cargo-target: ${{ matrix.config.target }}
      - name: Run cargo ${{ matrix.cargo_cmd.cmd_name }} ${{ matrix.cargo_cmd.args }}
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.cargo_cmd.cmd_name }}
          args: ${{ matrix.cargo_cmd.args }}
      - name: Archive vscan
        uses: actions/upload-artifact@v4
        with:
          name: vectorscan-sys-${{ matrix.config.target }}
          path: |
            **/target/*/deps/libvectorscan_sys*
            **/target/*/deps/vectorscan_sys*
            **/target/*/build/vectorscan-sys-*
            **/target/*/libvectorscan_sys*
