on: push
name: Check Code
jobs:
  check_code:
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ secrets.DD_SITE }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
            default: true
      - name: Check code with Clippy
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check
      - name: Run tests
        run: cargo test
      - name: Check python-best-practices ruleset
        run: cargo run --bin datadog-static-analyzer-test-ruleset  -- -r python-best-practices
      - name: Check python-security ruleset
        run: cargo run --bin datadog-static-analyzer-test-ruleset  -- -r python-security
      - name: Check python-code-style ruleset
        run: cargo run --bin datadog-static-analyzer-test-ruleset  -- -r python-code-style
