on: push
name: Check Code
jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
            default: true
      - name: Check code with Clippy
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check
      - name: Run tests
        run: cargo test
