on:
  push:
  pull_request:

name: Test Build
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
      DD_SITE: ${{ vars.DD_SITE }}
    steps:
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install -y build-essential cmake libboost-all-dev ragel
      - name: Install macOS build dependencies
        if: runner.os == 'macOS'
        run: brew install boost cmake ragel
      - name: 'windows: cache ragel'
        id: windows-cache-ragel
        if: runner.os == 'windows'
        uses: actions/cache@v4
        with:
          path: C:\vcpkg
          key: windows-msvc-ragel
      - name: 'windows: install ragel'
        if: runner.os == 'windows' && steps.windows-cache-ragel.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
          vcpkg install ragel:x64-windows
      - name: 'windows: install boost'
        id: windows-install-boost
        if: runner.os == 'windows'
        uses: MarkusJx/install-boost@v2.4.5
        with:
          toolset: msvc
          platform_version: 2022
          boost_version: 1.78.0
          boost_install_dir: ${{ runner.workspace }}
      - name: 'windows: configure env'
        if: runner.os == 'windows'
        run: |
          "C:\vcpkg\installed\x64-windows\tools" | Out-File -FilePath $env:GITHUB_PATH -Append
          "BOOST_ROOT=${{ steps.windows-install-boost.outputs.BOOST_ROOT }}" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - uses: actions/checkout@v4
      - name: Use cache for cargo build
        uses: Swatinem/rust-cache@v2.7.3
      - name: Build project
        run: cargo build --features datadog-static-analyzer/secrets
      - name: Archive bindings
        uses: actions/upload-artifact@v4
        with:
          name: vectorscan-sys-bindings-${{ matrix.target }}
          path: |
            **/bindings_*.rs
      - name: Compile tests
        run: cargo test --no-run
      - name: Run tests
        run: cargo test
