name: Software Composition Analysis

on:
  push:
    branches:
      - "**"

jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    name: Datadog SBOM Generation and Upload
    steps:
    - name: Get Datadog credentials
      id: dd-sts
      uses: DataDog/dd-sts-action@2e8187910199bd93129520183c093e19aa585c75 # v1.0.0
      with:
        policy: datadog-static-analyzer
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: ./.github/actions/set-up-rust
    - name: cargo install sbom
      run: cargo install --version 0.8.4 cargo-sbom
    - name: cargo generate sbom
      run: |
        cargo sbom --cargo-package static-analysis-kernel --output-format cyclone_dx_json_1_4 > static-analysis-kernel.json
        cargo sbom --cargo-package bins --output-format cyclone_dx_json_1_4 > bins.json
        cargo sbom --cargo-package cli --output-format cyclone_dx_json_1_4 > cli.json
        cargo sbom --cargo-package static-analysis-server --output-format cyclone_dx_json_1_4 > static-analysis-server.json
    - name: Generate SBOM and Upload
      id: software-composition-analysis
      uses: DataDog/datadog-sca-github-action@2cc1486ee1b07318ba608b86e40d124efa76ddb5 # main
      with:
        dd_api_key: ${{ steps.dd-sts.outputs.api_key }}
        dd_app_key: ${{ steps.dd-sts.outputs.app_key }}
        dd_site: ${{ vars.DD_SITE }}

