on: push
name: Check that the JSON schema for the configuration file matches the examples
jobs:
  test_json_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm install -g pajv
      - run: make -C schema
  test_static_analyzer_configuration_parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Stable + Rustfmt + Clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
          default: true
      - name: Run the test-config tool against the examples
        run: ./misc/test-configuration-file-examples.sh
